### DISCUSSION TITLE
How to use private gitlab project in Function build srcRepo?

### DISCUSSION THREAD

**Discussion by xiaocode** [OpenFunction/OpenFunction#324] [Q&A] [answered]
I want to read my private git repository in openfunction, but I can not find any examples.

**Comment by wanjunlei** [comment]
Create a secret with two keys, `username` and `password`, and use it at here.

https://github.com/OpenFunction/OpenFunction/blob/main/apis/core/v1beta1/function_types.go#L39

**Comment by wanjunlei** [comment, marked as answer]
reference it in `spec.build.srcRepo`

**Reply by benjaminhuo** [reply]
Like below?

```yaml
apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: function-sample
spec:
  version: "v2.0.0"
  image: "openfunctiondev/sample-go-func:v1"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  build:
    builder: openfunction/builder-go:latest
    env:
      FUNC_NAME: "HelloWorld"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/knative/hello-world-go"
      revision: "main"
      credentials:
         name: git-repo-secret
  serving:
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent 
    runtime: "knative"
```
