### ISSUE TITLE
[Discussion] Add the ability to control concurrency of functions

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/OpenFunction#165]
**Description**
In the actual running of the function, we may need to control the concurrency of the function.

The current serving engines of OpenFunction - Knative Serving and Dapr - both have the ability to control runtime concurrency. We need to express this in the Function CRD in some concise and explicit way (annotations, properties, etc.)

**Additional context**
Reference:
https://knative.dev/docs/serving/autoscaling/concurrency/
https://docs.dapr.io/operations/configuration/control-concurrency/

**Comment by lizzzcai** [comment]
for all these configs, are you planning to expose it as it is or have the OpenFunction own-defined parameters/annotations? like:
`autoscaling.openfunction.io/target: "200"` or `openfunction.io/app-max-concurrency: "1"`

then map to different annotations based on the serving engine used by the user.

openFunction has different serving engines. The users probably don't want to know and learn what is running underneath. Maybe it will be good if OpenFunction can abstract them and provide documentation for them. 

And a global Config will be very useful as well.

**Comment by benjaminhuo** [comment]
> for all these configs, are you planning to expose it as it is or have the OpenFunction own-defined parameters/annotations? like: `autoscaling.openfunction.io/target: "200"` or `openfunction.io/app-max-concurrency: "1"`
> 
> then map to different annotations based on the serving engine used by the user.
> 
> openFunction has different serving engines. The users probably don't want to know and learn what is running underneath. Maybe it will be good if OpenFunction can abstract them and provide documentation for them.
> 
> And a global Config will be very useful as well.

Good Point, we'll considering this @tpiperatgod @wanjunlei

**Comment by tpiperatgod** [comment]
If it is possible to pass these parameters through as much as possible I think it is the better solution, but maybe we have to use a high-level wrapper to handle them?

I will try to make a rough option first for reference and we can also talk about this in meeting.

**Comment by zhu733756** [comment]
Yeah.

**Comment by lizzzcai** [comment]
As a temporal solution maybe, can we allow adding `label` and `annotation` to the serving.

for example:

```yaml
apiVersion: core.openfunction.io/v1alpha2
kind: Function
metadata:
  name: hello-world-go
  labels:
    environment: dev
spec:
  version: "v1.0.0"
  image: "lizzzcai/sample-go-func:v0.4.0"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  build:
    builder: openfunction/builder:v1
    env:
      FUNC_NAME: "HelloWorld"
      FUNC_TYPE: "http"
    srcRepo:
      url: "https://github.com/lizzzcai/openfunction-samples.git"
      sourceSubPath: "hello-world-go"
  serving:
    runtime: Knative # default to Knative
    labels:
      environment: dev
    annotations:
      # knative
      autoscaling.knative.dev/minScale: "3"
      # dapr
      dapr.io/enabled: "true"
      dapr.io/app-id: "hello-world-go"
```
This can help for Knative serving backend. We can use knative annotations, and even enable dapr as well. Which can probably help this issue as well: https://github.com/OpenFunction/OpenFunction/issues/173


Once OpenFunction has its own abstracted parameters, you can overwrite the annotation for knative serving.
