### ISSUE TITLE
Refactoring OpenFuncAsync runtime definition

### ISSUE THREAD

**Issue by benjaminhuo** [OpenFunction/OpenFunction#184]
**Description**
Currently, the OpenFuncAsync runtime is defined as below:
```yaml
  serving:
    runtime: "OpenFuncAsync"
    openFuncAsync:
      dapr:
        inputs:
          - name: kafka
            component: kafka-receiver
            type: bindings
        outputs:
          - name: notify
            type: bindings
            component: notification-manager
            operation: "post"
        annotations:
          dapr.io/log-level: "debug"
        components:
          kafka-receiver:
            type: bindings.kafka
            version: v1
            metadata:
              - name: brokers
                value: "kafka-logs-receiver-kafka-brokers:9092"
              - name: authRequired
                value: "false"
              - name: publishTopic
                value: "logs"
              - name: topics
                value: "logs"
              - name: consumerGroup
                value: "logs-handler"
          notification-manager:
            type: bindings.http
            version: v1
            metadata:
              - name: url
                value: http://notification-manager-svc.kubesphere-monitoring-system.svc.cluster.local:19093/api/v2/alerts
      keda:
        scaledObject:
          pollingInterval: 15
          minReplicaCount: 0
          maxReplicaCount: 10
          cooldownPeriod: 30
          triggers:
            - type: kafka
              metadata:
                topic: logs
                bootstrapServers: kafka-logs-receiver-kafka-brokers.default.svc.cluster.local:9092
                consumerGroup: logs-handler
                lagThreshold: "10"
```
There are a few problems here:
- The `inputs` and `outputs` is function level fields and doesn't belong to ` dapr`
- The `dapr` part is actually function binding definitions, it's better to make it clear
- The `keda` part is actually function scale Options, and it's better to make it clear as well.

So maybe we can make changes like below:

```yaml
  serving:
    runtime: "OpenFuncAsync"
    openFuncAsync:
      inputs:
        - name: kafka
          component: kafka-receiver
          type: bindings
      outputs:
        - name: notify
          type: bindings
          component: notification-manager
          operation: "post"
      bindings:
        dapr:
          annotations:
            dapr.io/log-level: "debug"
          components:
            kafka-receiver:
              type: bindings.kafka
              version: v1
              metadata:
                - name: brokers
                  value: "kafka-logs-receiver-kafka-brokers:9092"
                - name: authRequired
                  value: "false"
                - name: publishTopic
                  value: "logs"
                - name: topics
                  value: "logs"
                - name: consumerGroup
                  value: "logs-handler"
            notification-manager:
              type: bindings.http
              version: v1
              metadata:
                - name: url
                  value: http://notification-manager-svc.kubesphere-monitoring-system.svc.cluster.local:19093/api/v2/alerts
      scaleOptions:
        keda:
          scaledObject:
            pollingInterval: 15
            minReplicaCount: 0
            maxReplicaCount: 10
            cooldownPeriod: 30
            triggers:
              - type: kafka
                metadata:
                  topic: logs
                  bootstrapServers: kafka-logs-receiver-kafka-brokers.default.svc.cluster.local:9092
                  consumerGroup: logs-handler
                  lagThreshold: "10"
```

Maybe we can simply remove the `dapr` and `keda` and use `bindings` and `scaleOptions` instead?
What do you think @wanjunlei @tpiperatgod ？

@tpiperatgod Do we need to change functions framework and builders besides the CRD and controller changes?

**Comment by tpiperatgod** [comment]
The logic of the CRD( and the controller) part is associated with the processing of the function-framework part through the OpenFunction Context.

The two parts can be considered decoupled unless the contextual structure changes.

**Comment by tpiperatgod** [comment]
>Maybe we can simply remove the dapr and keda and use bindings and scaleOptions instead?
What do you think @wanjunlei @tpiperatgod ？

I agree with adding `scaleOptions`, which would solve the problem in #173. I have suggested follows in the proposal https://hackmd.io/A-r2frbVTpiDhpfNc7ac2w:

> I would prefer to add a new property to `spec.serving` in function crd to support this feature, as it is a feature of the serving phase.

the property can be `spec.serving.scaleOptions`

For `bindings`, since we also support pubsub type input and output sources, I'd like to know if `spec.serving.bindings` refers to both bindings and pubsub type input and output sources or just bindings type input and output sources?

**Comment by benjaminhuo** [comment]
OK, you mean the scaleOptions could be applied to both the sync and async runtime
```yaml
      scaleOptions:
        minReplicaCount:  10                               # 
        maxReplicaCount:  100 
        knative:
          xx
        keda:
          scaledObject:
```
And yes `spec.serving.bindings` refers to both  dapr `bindings` and dapr `pubsub` 
The dapr `binding` docs said "Using bindings, you can trigger your app with events coming in from external systems, or interface with external systems", so dapr `bindings` and dapr `pubsub` are used for the same purpose in OpenFuncAsync runtime

**Comment by tpiperatgod** [comment]
> OK, you mean the scaleOptions could be applied to both the sync and async runtime
> 
> ```yaml
>       scaleOptions:
>         minReplicaCount:  10                               # 
>         maxReplicaCount:  100 
>         knative:
>           xx
>         keda:
>           scaledObject:
> ```


it can also be:

```yaml
// for keda
scaleOptions:
  keda:
    minReplicaCount:  10
    maxReplicaCount:  100

// for knative
scaleOptions:
  knative:
    minReplicaCount:  10
    maxReplicaCount:  100
```

**Comment by benjaminhuo** [comment]
> 
> it can also be:
> 
> ```yaml
> // for keda
> scaleOptions:
>   keda:
>     minReplicaCount:  10
>     maxReplicaCount:  100
> 
> // for knative
> scaleOptions:
>   knative:
>     minReplicaCount:  10
>     maxReplicaCount:  100
> ```

A function can only use one runtime, so setting min/maxReplicaCount just once is ok

**Comment by benjaminhuo** [comment]
So the CRD looks like below now:
```yaml
  serving:
    runtime: "OpenFuncAsync"
    bindings:
      dapr:
        annotations:
          dapr.io/log-level: "debug"
        components:
          kafka-receiver:
            type: bindings.kafka
            version: v1
            metadata:
              - name: brokers
                value: "kafka-logs-receiver-kafka-brokers:9092"
              - name: authRequired
                value: "false"
              - name: publishTopic
                value: "logs"
              - name: topics
                value: "logs"
              - name: consumerGroup
                value: "logs-handler"
          notification-manager:
            type: bindings.http
            version: v1
            metadata:
              - name: url
                value: http://notification-manager-svc.kubesphere-monitoring-system.svc.cluster.local:19093/api/v2/alerts
    scaleOptions:
      minReplicaCount: 1
      maxReplicaCount:  10
      keda:
        scaledObject:
          pollingInterval: 15
          minReplicaCount: 0 // will overwrite the min/max params above
          maxReplicaCount: 10 // will overwrite the min/max params above
          cooldownPeriod: 30
          triggers:
            - type: kafka
              metadata:
                topic: logs
                bootstrapServers: kafka-logs-receiver-kafka-brokers.default.svc.cluster.local:9092
                consumerGroup: logs-handler
                lagThreshold: "10"
    openFuncAsync:
      inputs:
        - name: kafka
          component: kafka-receiver
          type: bindings
      outputs:
        - name: notify
          type: bindings
          component: notification-manager
          operation: "post"
```

**Comment by benjaminhuo** [comment]
We'd better investigate scale options of knative, keda, and keda-http to make the scaleoptions more common:
- knative https: //knative.dev/docs/serving/autoscaling/
- keda: https://keda.sh/docs/2.5/concepts/scaling-deployments/  
             https://keda.sh/docs/2.5/concepts/scaling-jobs/
- keda-http: https://github.com/kedacore/http-add-on/blob/main/examples/v0.2.0/httpscaledobject.yaml

And we needn't to follow keda's definition to minReplicaCount and maxReplicaCount, maybe we can just call it minReplicas/maxReplicas 
@tpiperatgod @wanjunlei

**Comment by tpiperatgod** [comment]
I have made some adjustments to `spec.serving.scaleOptions` and `spec.serving.runtime`:
```yaml
apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: function-sample
spec:
  serving:
    scaleOptions:
      min: 1
      max: 10
      keda:
        scaledJob:
          pollingInterval: 30
          maxReplicaCount: 10
        scaledObject:
          pollingInterval: 30
          cooldownPeriod: 30
          minReplicaCount: 0
          maxReplicaCount: 10
      knative:
        autoscaling:
          target: 200
          max-scale: 3
          min-scale: 1
    runtime:
      async:
        inputs:
          - name: kafka
            component: kafka-receiver
            type: bindings
        outputs:
          - name: nats
            component: nats-eventbus
            type: pubsub
      sync:
        outputs:
          - name: kafka
            component: kafka-receiver
            type: bindings
      knative:
        outputs:
          - name: kafka
            component: kafka-receiver
            type: bindings
    bindings:
      annotations:
        dapr.io/log-level: "debug"
      components:
        kafka-receiver:
          type: bindings.kafka
          version: v1
          metadata:
            - name: brokers
              value: "kafka-logs-receiver-kafka-brokers:9092"
            - name: authRequired
              value: "false"
            - name: publishTopic
              value: "logs"
            - name: topics
              value: "logs"
            - name: consumerGroup
              value: "logs-handler"
    pubsub:
      annotations:
        dapr.io/log-level: "debug"
      components:
        kafka-receiver:
          type: pubsub.natsstreaming
          version: v1
          metadata:
            - name: brokers
              value: "nats:8222"
            - name: authRequired
              value: "false"
            - name: publishTopic
              value: "eventbus"
            - name: topics
              value: "eventbus"
            - name: consumerGroup
              value: "eventbus"
    template:
      containers:
        - name: function
          imagePullPolicy: Always
```
