### ISSUE TITLE
Add bindings to knative sync functions

### ISSUE THREAD

**Issue by benjaminhuo** [OpenFunction/OpenFunction#185]
**Description**
Currently, OpenFuncAsync functions can not be triggered by HTTP, we need to add HTTP trigger for Async functions.

The idea is:
1. Use Knative sync functions to receive an event in plain JSON or CloudEvent format
2. Send the received event to a dapr output binding or pubsub component, most likely a MQ such as Kafka or NATS
3. Trigger an async function from the MQ

So we need to add dapr output bindings or pubsub to knative sync functions like below:

```yaml
  serving:
    runtime: "Knative"
    bindings:
      dapr:
        annotations:
          dapr.io/log-level: "debug"
        components:
          kafka-receiver:
            type: bindings.kafka
            version: v1
            metadata:
              - name: brokers
                value: "kafka-logs-receiver-kafka-brokers:9092"
              - name: authRequired
                value: "false"
              - name: publishTopic
                value: "logs"
              - name: topics
                value: "logs"
              - name: consumerGroup
                value: "logs-handler"
    scaleOptions:
      minReplicaCount: 1
      maxReplicaCount:  10
    knative:
      outputs:
        - name: kafka
          component: kafka-receiver
          type: bindings
```

Knative with dapr enabled sample can be found here: https://github.com/dapr/samples/tree/master/knative-distributed-calculator

**Comment by tpiperatgod** [comment]
I have made some adjustments to `spec.serving.scaleOptions` and `spec.serving.runtime`:
```yaml
apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: function-sample
spec:
  serving:
    scaleOptions:
      min: 1
      max: 10
      keda:
        scaledJob:
          pollingInterval: 30
          maxReplicaCount: 10
        scaledObject:
          pollingInterval: 30
          cooldownPeriod: 30
          minReplicaCount: 0
          maxReplicaCount: 10
      knative:
        autoscaling:
          target: 200
          max-scale: 3
          min-scale: 1
    runtime:
      async:
        inputs:
          - name: kafka
            component: kafka-receiver
            type: bindings
        outputs:
          - name: nats
            component: nats-eventbus
            type: pubsub
      sync:
        outputs:
          - name: kafka
            component: kafka-receiver
            type: bindings
      knative:
        outputs:
          - name: kafka
            component: kafka-receiver
            type: bindings
    bindings:
      annotations:
        dapr.io/log-level: "debug"
      components:
        kafka-receiver:
          type: bindings.kafka
          version: v1
          metadata:
            - name: brokers
              value: "kafka-logs-receiver-kafka-brokers:9092"
            - name: authRequired
              value: "false"
            - name: publishTopic
              value: "logs"
            - name: topics
              value: "logs"
            - name: consumerGroup
              value: "logs-handler"
    pubsub:
      annotations:
        dapr.io/log-level: "debug"
      components:
        kafka-receiver:
          type: pubsub.natsstreaming
          version: v1
          metadata:
            - name: brokers
              value: "nats:8222"
            - name: authRequired
              value: "false"
            - name: publishTopic
              value: "eventbus"
            - name: topics
              value: "eventbus"
            - name: consumerGroup
              value: "eventbus"
    template:
      containers:
        - name: function
          imagePullPolicy: Always
```
