### ISSUE TITLE
Replace the sink.ref in events api with function ingress

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/OpenFunction#198]
**Description**
Since we already have the Function Ingress, we can use it instead of `sink.ref` in the events API.

**Additional context**
If not, we would have to configure the Knative Serving network layer (e.g. kourier)
Using the Function Ingress can help us shield the underlying complex implementation for the user.

**Comment by benjaminhuo** [comment]
What does sink.ref looks like now?

**Comment by tpiperatgod** [comment]
like this:
```yaml
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: serving-d2blp-ksvc-2hbp6
      namespace: default
```
