### ISSUE TITLE
Support building function images from Dockerfile

### ISSUE THREAD

**Issue by benjaminhuo** [OpenFunction/OpenFunction#204]
**Description**
We can extract the application template from the builders and make it a base image, from which we can build function images with a dockerfile and then copy the built binary to the run image.
 

**Additional context**
This is a complimentary build approach for the buildpacks approach

**Comment by lizzzcai** [comment]
Building from dockerfile is a nice feature and it can provide more flexibility to users.

The current build from source is not so optimized. I tried to build the same `hello world` program, one is `from source` and another is `from dockerfile`. For image built from dockerfile, the image size is about 1.9MB. For image built from source, the size is about 260MB. Hopefully, it can be optimized in the future.


A side topic, I want to check if OpenFunction can support customized `run image`. The target here is to reduce the image size so that can reduce the cool start time.

Usecase: 
for machine learning use cases, there are usually a lot of dependencies like tensorflow, pytorch, opencv etc. The size of these kinds of libraries are quite big (up to 1-2 GB usually) and the actual code is about 1-2 MB (not including the models). If the base libraries can be separated and cached in the host machine, I think that will help to reduce the cool start time.

A similar result is shown in this [post](https://github.com/kleveross/ormb/blob/master/docs/introduction.md) for your reference.

An example function yaml:

```yaml
apiVersion: core.openfunction.io/v1alpha2
kind: Function
metadata:
  name: iris-python
spec:
  version: "v1.0.0"
  image: "lizzzcai/iris-python-func:v0.4.0"
  imageCredentials:
    name: push-secret
  port: 8080
  runImage: tensorflow/tensorflow:2.2.3-py3 # dependencies to run the python code
  build:
    builder: openfunction/builder:v1
    env:
      FUNC_NAME: "predict"
      FUNC_TYPE: "http"
      FUNC_SRC: "main.py"
    srcRepo:
      url: "https://github.com/lizzzcai/openfunction-samples.git"
      sourceSubPath: "iris-python"
  serving:
    runtime: Knative
```
I can create a feature request for this if needed.
