### ISSUE TITLE
Request feature to preload the run image to nodes to reduce the cold start time

### ISSUE THREAD

**Issue by lizzzcai** [OpenFunction/OpenFunction#217]
**Description**

I would like to check if OpenFunction can support customized run images and cache the run images in the host. The target here is to reduce the image size so that can reduce the cool start time.

### Use case
for machine learning use cases, there are usually a lot of dependencies like tensorflow, pytorch, opencv etc. The size of these kinds of libraries are quite big (up to 1-2 GB usually) and the actual size of code is about 1-2 MB (not including the models). If the base libraries can be separated and cached in the host machine, The image size of the function can be reduced. I think that will help to reduce the cool start time significantly.

A similar idea is shown in this [post](https://github.com/kleveross/ormb/blob/master/docs/introduction.md) for your reference.

An example function yaml for illustration:
```yaml
apiVersion: core.openfunction.io/v1alpha2
kind: Function
metadata:
  name: iris-python
spec:
  version: "v1.0.0"
  image: "lizzzcai/iris-python-func:v0.4.0"
  imageCredentials:
    name: push-secret
  port: 8080
  # user can define the run image
  runImage: tensorflow/tensorflow:2.2.3-py3 # dependencies to run the python code
  build:
    builder: openfunction/builder:v1
    env:
      FUNC_NAME: "predict"
      FUNC_TYPE: "http"
      FUNC_SRC: "main.py"
    srcRepo:
      url: "https://github.com/lizzzcai/openfunction-samples.git"
      sourceSubPath: "iris-python"
  serving:
    runtime: Knative
```
