### ISSUE TITLE
Function failed to build after renaming the used secret

### ISSUE THREAD

**Issue by lizzzcai** [OpenFunction/OpenFunction#219]
**Description**
Function failed to build after renaming or deleting the secret used previously

**Environmental**
Tell us what your cluster environment is like, e.g.

- Operating System Information
- kubernetes version: 1.21.5
- OpenFunction version: latest
- Versions of dependent components (e.g. dapr, keda, shipwright, knative)
  - Shipwright: v0.6.0

**Expected behavior**
The Function should be able to build even the push secret being deleted

**Actual behavior**
Once I delete the push-secret and create another secret with a different name (push-secret-new), ofn is not able to build the function

**To Reproduce**

1. create a push secret: `push-secret`
2. build a function
```yaml
apiVersion: core.openfunction.io/v1alpha2
kind: Function
metadata:
  name: function-sample
spec:
  version: "v1.0.0"
  image: "openfunctiondev/sample-go-func:latest"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  build:
    builder: openfunction/builder:v1
    env:
      FUNC_NAME: "HelloWorld"
      FUNC_TYPE: "http"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/Knative/hello-world-go"
  serving:
    runtime: "Knative" # default to Knative
    template:
      containers:
        - name: function
          imagePullPolicy: Always
```
3. delete the `push-secret` and create a new one called: `push-secret-new`
4. build the function again
```yaml
apiVersion: core.openfunction.io/v1alpha2
kind: Function
metadata:
  name: function-sample-new
spec:
  version: "v1.0.0"
  image: "openfunctiondev/sample-go-func:latest"
  imageCredentials:
    name: push-secret-new # <-update the secret
  port: 8080 # default to 8080
  build:
    builder: openfunction/builder:v1
    env:
      FUNC_NAME: "HelloWorld"
      FUNC_TYPE: "http"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/Knative/hello-world-go"
  serving:
    runtime: "Knative" # default to Knative
    template:
      containers:
        - name: function
          imagePullPolicy: Always
```
5. See error
```
❯ k get buildrun
NAME                           SUCCEEDED   REASON           STARTTIME   COMPLETIONTIME
builder-lckjg-buildrun-mpgq4   False       CouldntGetTask   2m1s        2m1s

...
    conditions:
    - lastTransitionTime: "2022-01-14T09:17:13Z"
      message: 'failed to create task run pod "builder-lckjg-buildrun-mpgq4-wqfwp":
        translating TaskSpec to Pod: secrets "push-secret" not found. Maybe invalid
        TaskSpec'
      reason: CouldntGetTask
      status: "False"
      type: Succeeded
```

**Screenshots**

**Additional context**

It is an issue from Shipwright, please refer to this issue: https://github.com/shipwright-io/build/issues/969
