### ISSUE TITLE
Add the parameter validation capabilities for Function.

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/OpenFunction#274]
## Motivation

In OpenFunction, the `Function` CRD is used to manage the lifecycle of functions, dividing the process into the **build phase** and the **serving phase**.

In general, after creating the function, it enters the build phase, waits for the build to complete and produces the OCI image, and then enters the serving phase to create the workload.

The build phase tends to take longer, and if the parameters provided to the service phase are invalid. The user only finds out if the function will work after a period of time, not just after it has been created.

Therefore, we need to add the parameter checking capability to the `Function` CRD so that it can check the parameters for all phases at the beginning of the `Function` creation in order to make the user experience more user-friendly.

## Goals

Our goal is to validate the parameters of the **build phase** and serving phase when creating the `Function` resource in the following manners：

- Compliance with specifications, i.e., verifying that the parameters conform to certain specifications, such as whether they are within the range of available values
- Validity Verification, i.e., verifying that the parameters are valid, which usually involves the association between multiple parameters, such as the minimum number of copies should not be greater than the maximum number of copies, and an "either/or" scenario between two parameters

## Proposal

```yaml
apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: {function-name}
spec:
  version: # Optional, function version, default value is "latest"
  image: # Mandatory, container image url address, refer to: https://cloud.google.com/artifact-registry/docs/docker/names; if `spec.build` is set, the build phase will be completed first and the container image will be created or export to the repository; if `spec.build` is not set, the container image will be used directly
  imageCredentials:
    name: # the name of the secret resource, mandatory when `spec.build` is enabled or when pulling images from a repository that requires authentication
  build:
    builder: # Optional, the builder image url address, refer to: https://cloud.google.com/artifact-registry/docs/docker/names; note that only one of `build.dockerfile` and `build.builder` will take effect
    env:
      key: value # Optional, environment variables for the build phase
    params:
      key: value # Optional, parameters passed to Shipwright
    srcRepo:
      url: # Optional, address of the source code repository
      sourceSubPath: # Optional, the subpath of the source code repository, the default value is the root directory
      revision: # Optional, the revision value of the source code repository, the default value is empty
      credentials:
        name: # the name of the secret resource, mandatory when pulling code from a source code repository that requires authentication
    dockerfile: # Optional，the name of the dockerfile file in the subpath directory of the source code repository; note that only one of `build.dockerfile` and `build.builder` will take effect
    timeout: # Optional, timeout settings for the build phase, not less than 0 
    successfulBuildsHistoryLimit: # Optional, the maximum number of successful build histories retained, which cannot be less than 0 and defaults to 0
    failedBuildsHistoryLimit: # Optional，the maximum number of failed build histories retained, which cannot be less than 0 and defaults to 1
    builderMaxAge: # Optional, builder cr retention time, cannot be less than 0, default is 0, means do not delete builder cr
    shipwright:
      strategy:
        name: # Optional, the name of the build strategy, a build strategy with the corresponding name must already exist
        kind: # Optional, the type of the build strategy, available values are "BuildStrategy", "ClusterBuildStrategy", default is "BuildStrategy"
      timeout: # Optional, timeout setting for Shipwright's Buildrun resource, not less than 0 
  serving:
    scaleOptions:
      maxReplicas: # Optional, maximum number of replicas for autoscaling, must be greater than `scaleOptions.minReplicas`; this value will be overridden by the corresponding configuration in `scaleOptions.keda` or `scaleOptions.knative`
      minReplicas: # Optional, minimum number of replicas for autoscaling, must be less than `scaleOptions.maxReplicas` and cannot be less than 0; this value will be overridden by the corresponding configuration in `scaleOptions.keda` or `scaleOptions.knative`
      knative:
      	key: value # Optional, autoscaling parameters for knative
      keda:
        scaledJob:
          restartPolicy: # Optional, restart policy for job container, available values are "Always", "OnFailure", "Never", default is "Always"
          pollingInterval: # Optional, the period of scaler trigger condition check, if set then value must be greater than 0, defaults to 30
          successfulJobsHistoryLimit: # Optional, the maximum number of successful job histories retained, cannot be less than 0, default is 100
          failedJobsHistoryLimit: # Optional，the maximum number of failed job histories retained, cannot be less than 0, default is 100
          maxReplicaCount: # Optional, the maximum number of replicas when autoscaling, cannot be less than 0, default is 100
          scalingStrategy:
            strategy: # Optional, autoscaling strategy type, available values are "default", "custom", "accurate", default is "default"
            customScalingQueueLengthDeduction: # Mandatory if `scalingStrategy.strategy` is "custom", cannot be less than 0
            customScalingRunningJobPercentage: # Mandatory if `scalingStrategy.strategy` is "custom", in percentage format
        scaledObject:
          workloadType: # Optional, type of the scalable workload, available values are "Deployment", "StatefulSet", default is "Deployment"
          pollingInterval: # Optional，the period of scaler trigger condition check, if set then value must be greater than 0, defaults to 30
          cooldownPeriod: # Optional，the period to wait after the last trigger reported active before scaling the resource back to 0, defaults to 300 (5m)
          minReplicaCount: # Optional, the minimum number of replicas for autoscaling, if set then the value cannot be less than 0 and must be less than `scaledObject.maxReplicaCount`, defaults to 0
          maxReplicaCount: # Optional, the maximum number of replicas for autoscaling, if set must be greater than `scaledObject.minReplicaCount`, defaults to 100
          advanced:
            restoreToOriginalReplicaCount: # Optional, indicates whether to return to the original number of replicas after a scaledObject is deleted, default is false
            horizontalPodAutoscalerConfig:
              behavior:
                scaleUp:
                  stabilizationWindowSeconds: # Optional, stabilization window for the HPA phase (1<->N), if set the value must not be less than 0 and not greater than 3600
                  selectPolicy: # Optional, HPA's scaling selection policy, available values are "Max", "Min", "Disabled", default value is "Max"
                  policies:
                    - type: # Mandatory if enabled, type of scaling policy for HPA, available values are "Pods", "Percent"
                      value: # Mandatory if enabled, the value of the HPA's scaling policy
                      periodSeconds: # Mandatory if enabled, indicates the length of time in the past for which the policy must hold true, must be greater than 0
                scaleDown:
                  stabilizationWindowSeconds: # Optional, stabilization window for the HPA phase (1<->N), if set the value must not be less than 0 and not greater than 3600
                  selectPolicy: # Optional, HPA's scaling selection policy, available values are "Max", "Min", "Disabled", default value is "Max"
                  policies:
                    - type: # Mandatory if enabled, type of scaling policy for HPA, available values are "Pods", "Percent"
                      value: # Mandatory if enabled, the value of the HPA's scaling policy
                      periodSeconds: # Mandatory if enabled, indicates the length of time in the past for which the policy must hold true, must be greater than 0
    inputs:
      - name: # Mandatory, the name of the function input that will be used in the user function
        component: # Mandatory, the name of the component associated with the function input
        topic: # Optional, the topic name of the function input, mandatory if the function input is a Dapr Pubsub component
        params:
        	key: value # Optional, the parameters passed to the component associated with the function input
        operation: # Optional, the operation configuration of the component associated with the function input
    outputs:
      - name: # Mandatory, the name of the function output that will be used in the user function
        component: # Mandatory, the name of the component associated with the function output
        topic: # Optional, the topic name of the function output, mandatory if the function output is a Dapr Pubsub component
        params:
        	key: value # Optional, the parameters passed to the component associated with the function output
        operation: # Optional, the operation configuration of the component associated with the function output
    template: # Optional, Pod specification template
    runtime: # Mandatory, available values "knative", "async"
    bindings:
      key: # Mandatory if enabled, the name of the bindings component, cannot use the same name as the pubsub component.
        type: # Mandatory, types of bindings component, refer to: https://docs.dapr.io/reference/components-reference/supported-bindings/
        version: # Mandatory, version of the bindings component, default is "v1"
        metadata: # Mandatory, configuration for the bindings component, refer to: https://docs.dapr.io/reference/components-reference/supported-bindings/
        - name: # Mandatory, the name of the configuration
          value: # Mandatory, the value of the configuration
    pubsub:
      key: # Mandatory if enabled, the name of the pubsub component, cannot use the same name as the bindings component.
        type: # Mandatory, types of bindings component, refer to: https://docs.dapr.io/reference/components-reference/supported-pubsub/
        version: # Mandatory, version of the pubsub component, default is "v1"
        metadata: # andatory, configuration for the pubsub component, refer to: https://docs.dapr.io/reference/components-reference/supported-pubsub/
        - name: # Mandatory, the name of the configuration
          value: # Mandatory, the value of the configuration
    triggers:
      - type: # Mandatory, types of trigger, refer to: https://keda.sh/docs/2.6/scalers/
        name: # Optional, the name of the trigger, don't know its use yet
        metadata: # Mandatory, the configuration of the trigger, refer to: https://keda.sh/docs/2.6/scalers/
          key: value
        authenticationRef:
          name: # Mandatory if enabled, the name of the trigger authentication resource
          kind: # Optional, the kind of trigger authentication resource, available values are "TriggerAuthentication", "ClusterTriggerAuthentication", the default value is "TriggerAuthentication"
        fallback: # Optional, the number of replicas to fall back on after a failed trigger, must be greater than 0
        targetKind: # Optional, the types of the trigger target, the available values are "object", "job", the default is "object"
    params:
      key: value # Optional, parameters passed to the serving phase; will be passed to the pod as environment variables
    labels:
      key: value # Optional, labels for the target workload
    annotations:
      key: value # Optionally, annotations for the target workload
    timeout: # Optional, timeout settings for the serving phase, not less than 0 
```

The parameter validation solution based on the `Function` CRD description above is as follows:

- spec.build phase
  1. One of `spec.build.builder` and `spec.build.dockerfile` must exist and use `spec.build.builder` in preference
  2. Validation rules for the `spec.build.srcRepo` structure:
     - `url` cannot be ""
     - `sourceSubPath` is the root directory, i.e. "/" by default
     - `revision` is "" by default
  3. `spec.build.timeout` optional, if set, it cannot be less than 0, not set and set to 0 means timeout is not enabled
  4. `spec.build.successfulBuildsHistoryLimit` optional, if set, it cannot be less than 0. The default is 0 which means no build success history will be kept
  5. `spec.build.failedBuildsHistoryLimit` optional, if set, it cannot be less than 0. The default is 1, which means that only the most recent build failure history will be kept
  6. `spec.build.builderMaxAge` optional, if set, it can not be less than 0, the default is 0 means do not delete the builder cr
  7. Validation rules for the `spec.build.shipwright` structure:
     - `strategy.kind` optional, if set then the value needs to be in the scope of "BuildStrategy", "ClusterBuildStrategy"; default is "BuildStrategy"
- spec.serving phase
  1. `spec.serving.runtime` mandatory, value needs to be in the scope of "knative", "async"
  2. Validation rules for the `spec.serving.scaleOptions` structure:
     - `maxReplicas` optional, default is 10, cannot be less than `minReplicas`
     - `minReplicas` optional, default is 0, cannot be greater than `maxReplicas` and cannot be less than 0
     - Validation rules for the `keda` structure:
       - `keda.scaledJob` and `keda.scaledObject` have at most one enabled, with preference to `keda.scaledJob`
       - If `keda.scaledObject` is enabled:
         - `scaledObject.workloadType` optional, if set then the value needs to be in the scope of "Deployment", "StatefulSet"; default is "Deployment"
         - `scaledObject.pollingInterval` optional, if set then the value must not be less than 0, default is 30
         - `scaledObject.cooldownPeriod` optional, if set then the value cannot be less than 0, default is 300
         - `scaledObject.minReplicaCount` optional, if set, the value cannot be less than 0 and must be less than `scaledObject.maxReplicaCount`, default is 0
         - `scaledObject.maxReplicaCount` optional, if set, the value cannot be less than `scaledObject.minReplicaCount`, default is 100
         - `scaledObject.advanced` optionally, the verification can be done by creating an instance of this structure
       - If `keda.scaledJob` is enabled：
         - `scaledJob.restartPolicy` optional, if set then the value needs to be in the scope of "Always", "OnFailure", "Never"; default is "Always"
         - `scaledJob.pollingInterval` optional, if set then the value must not be less than 0, default is 30
         - `scaledJob.successfulJobsHistoryLimit` optional, if set then the value cannot be less than 0, default is 100
         - `scaledJob.failedJobsHistoryLimit` optional, if set then the value cannot be less than 0, default is 100
         - `scaledJob.maxReplicaCount` optional, if set the value must be greater than 0, default is 100
         - `scaledJob.scalingStrategy` optionally, the verification can be done by creating an instance of this structure
     - Validation rules for the `knative` structure：
       - Its `key` should be in the scope of "min-scale" (v1.1 and later), "max-scale" (v1.1 and later), "minScale " (before v1.1), "maxScale" (before v1.1)
  3. Validation rules for the `spec.serving.inputs`、`spec.serving.outputs` structures:
     - `component` mandatory, needs to match with `spec.serving.bindings` and `spec.serving.pubsub`, the matching rules are as follows:
       - The value of `component` must be in the set of the `key` of `spec.serving.bindings` and `spec.serving.pubsub`, which is the name of the component
     - The other fields I think can be left unvalidated and recommend refer to Dapr's documentation
  4. Validation rules for the `spec.serving.bindings`、`spec.serving.pubsub` structures:
     - `key` is the component name, follow the validation rules of the previous article to verify the relevance
     - `type` mandatory, requires validation against available types provided by Dapr bindings, Dapr pubsub
     - The other fields I think can be left unvalidated and recommend refer to Dapr's documentation
  5. Validation rules for the `spec.serving.triggers` structure:
     - `type` mandatory, requires verification based on the types of scaler provided by KEDA
     - `authenticationRef.kind` optional, if set, the value should be in the scope of "TriggerAuthentication", "ClusterTriggerAuthentication"; default is "TriggerAuthentication"
     - `fallback` optional, if set then the value should not be less than 0, default is 0
     - `targetKind` optional, if set then the value should be in the scope of "object", "job"; default is "object"
  6. `spec.serving.timeout` optional, if set, it cannot be less than 0, not set and set to 0 means timeout is not enabled
