### ISSUE TITLE
'function' is the only valid spec.serving.template.containers[0].name

### ISSUE THREAD

**Issue by zylan29** [OpenFunction/OpenFunction#286]
**Description**
After several round tests, I found that 'function' is the only valid `spec.serving.template.containers[0].name`. If changed the name to other values, it will be stuck in `Starting` SERVINGSTATE. 

For example, the following yml will fail
```
apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: go-function-sample
spec:
  version: "v2.0.0"
  image: "harbor.kubeone.local/sample-go-func:latest"
  #imageCredentials:
  #name: harbor-secret
  port: 8080 # default to 8080
  build:
    builder: openfunction/builder-go:latest
    env:
      FUNC_NAME: "HelloWorld"
      FUNC_CLEAR_SOURCE: "true"
      GOPROXY: "https://proxy.golang.com.cn,direct"
    srcRepo:
      url: "https://gitee.com/zylan29/openfunction-samples.git"
      sourceSubPath: "functions/knative/hello-world-go"
      #revision: "master"
  serving:
    template:
      containers:
        - name: go-function
          image: "harbor.kubeone.local/sample-go-func:latest"
          imagePullPolicy: Always
    runtime: "knative"
```

```
~ kubectl get functions.core.openfunction.io
NAME                 BUILDSTATE   SERVINGSTATE   BUILDER         SERVING         URL   AGE
go-function-sample   Succeeded    Starting       builder-w8p4x   serving-xmpqm         7m53s

~ kubectl get ksvc                          
NAME                       URL                                                            LATESTCREATED                   LATESTREADY           READY   REASON
helloworld-go              http://helloworld-go.default.10.233.57.212.nip.io              helloworld-go-00001             helloworld-go-00001   True    
serving-xmpqm-ksvc-dqjj8   http://serving-xmpqm-ksvc-dqjj8.default.10.233.57.212.nip.io   serving-xmpqm-ksvc-dqjj8-v200                         False   RevisionMissing
```
The serving pod throws errors:
```
E0509 02:20:05.390902       1 framework.go:41] failed to parse OpenFunction FunctionContext: env FUNC_CONTEXT not found

 F0509 02:20:05.390936       1 main.go:24] env FUNC_CONTEXT not found
```

Simply changing spec.serving.template.containers[0].name from `go-function` back to `function` will work.

I am not sure this is a bug or a feature.

**Environmental**
Tell us what your cluster environment is like, e.g.
```
kubernetes: 1.21.5
openFunction: 0.6.0
knativeServing: 1.0.1
kourier: 1.0.1
defaultDomain: 1.0.1
keda: 2.4.0
dapr: 1.5.1
tektonPipelines: 0.30.0
shipwright: 0.6.1
certManager: 1.5.4
ingress: 1.1.0
```
