### ISSUE TITLE
Function builder error

### ISSUE THREAD

**Issue by ZoeShaw101** [OpenFunction/OpenFunction#317]
**Description**
deploy demo function https://github.com/OpenFunction/samples/tree/main/functions/knative/hello-world-go to the cluster, but  got build error

```
➜  hello-world-go git:(main) ✗ kubectl get functions.core.openfunction.io

NAME              BUILDSTATE   SERVINGSTATE   BUILDER         SERVING   URL   AGE
function-sample   Failed                      builder-xpn44                   8m20s
```

ofn logs got this log:

<img width="1440" alt="Screen Shot 2022-07-10 at 5 50 49 PM" src="https://user-images.githubusercontent.com/13792102/178139853-2c1eea20-3cff-4aa0-99ff-9bb5e9c79844.png">

**Environmental**

- Operating System Information : Mac OS
- kubernetes version: minikube version: v1.18.1
- OpenFunction version : 

<img width="490" alt="Screen Shot 2022-07-10 at 5 54 39 PM" src="https://user-images.githubusercontent.com/13792102/178139949-fba24687-28c0-4e94-b020-9a80340f3fcf.png">

**Comment by benjaminhuo** [comment]
@ZoeShaw101 You need to set go proxy like below:

```yaml
  build:
    builder: openfunction/builder-go:latest
    env:
      FUNC_NAME: "xx"
      FUNC_CLEAR_SOURCE: "true"
      # Use FUNC_GOPROXY to set the goproxy
      FUNC_GOPROXY: "https://goproxy.cn"
```
