### ISSUE TITLE
How can openfunction interact with private harbor

### ISSUE THREAD

**Issue by liililil** [OpenFunction/OpenFunction#334]
**Description**
Yesterday I saw that openfunction supports java11 builder (openfunction/builder-java:v2-11) in https://openfunction.dev/docs/concepts/function_build/, and then I tried to use it to build a java function to image (https://github.com/OpenFunction/functions-framework-java) and built success.
But today I can't find openfunction/builder-java:v2-11 any more in docker hub, so I try to push it to private harbor and then use the builder-java in private harbor. And there's something wrong with the taskrun, I want to know that how can I define the imagePullSecrets.

**Environmental**
- Operating System Information
- kubernetes version 1.20.4
- OpenFunction version  0.6.0
- Versions of dependent components (e.g. dapr, keda, shipwright, knative)

**Expected behavior**
The spec.imageCredentials.name or other configuration can support the secret to pull the builder from private harbor.

**Actual behavior**
I can't find other configuration, and only define spec.imageCredentials.name.
The pod ImagePullBackOff, and the step "step-create" has error.
```
Events:
  Type     Reason   Age                    From     Message
  ----     ------   ----                   ----     -------
  Normal   Pending  20m (x14 over 67m)     TaskRun  build step "step-create" is pending with reason "Back-off pulling image \"harbor-xxx/xxx/builder-java:v2-11\""
  Normal   Pending  10m (x16 over 67m)     TaskRun  build step "step-create" is pending with reason "rpc error: code = Unknown desc = Error response from daemon: unauthorized: unauthorized to access repository: xxx/builder-java, action: pull: unauthorized to access repository: xxx/builder-java, action: pull"
  Warning  Failed   7m34s (x2 over 7m34s)  TaskRun  TaskRun "builder-k5t9c-buildrun-vnxhj-bn7v6" failed to finish within "1h0m0s"
```
There is no imagePullSecrets in the pod or taskrun, how can I define?

**To Reproduce**
1. docker-registry:
kubectl create secret docker-registry docker-registry --docker-server=harbor-xxx/xxx  --docker-username='xxx' --docker-password='xxx' -n openfunction
2. function.yaml:
```
apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: function-sample
  annotations:
    plugins: |
      pre:
      - dev.openfunction.samples.plugins.ExamplePlugin
      post:
      - dev.openfunction.samples.plugins.ExamplePlugin
spec:
  version: "v2.0.0"
  image: "harbor-xxx/xxx/sample-java-func:v1" # The image name
  imageCredentials:
    name: docker-registry # The customized docker-registry
  port: 8080
  build:
    builder: harbor-xxx/xxx/builder-java:v2-11 # The builder in private harbor
    env:
      FUNC_NAME: "dev.openfunction.samples.HttpFunctionImpl"
      FUNC_CLEAR_SOURCE: "true"
      GOOGLE_FUNCTION_SIGNATURE_TYPE: "http"
    srcRepo:
      url: "https://github.com/OpenFunction/functions-framework-java.git"
      sourceSubPath: "samples"
      revision: "master"
  serving:
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
    runtime: "knative"
```
kubectl apply -f function.yaml -n openfunction
3. kubectl get po -n openfunction / kubectl get taskrun -n openfunction

**Screenshots**

**Additional context**

**Comment by benjaminhuo** [comment]
> But today I can't find openfunction/builder-java:v2-11 any more in docker hub

@liililil The builder-java:v2-11 is still there in dockerhub

![image](https://user-images.githubusercontent.com/18525465/181218090-159f9098-b92d-4fe9-b899-b18765b75f67.png)

**Comment by benjaminhuo** [comment]
We do need to support private harbor @wanjunlei

**Comment by wanjunlei** [comment]
> We do need to support private harbor @wanjunlei

Ok, I will look into this.

**Comment by liililil** [comment]
> > But today I can't find openfunction/builder-java:v2-11 any more in docker hub
> 
> @liililil The builder-java:v2-11 is still there in dockerhub
> 
@benjaminhuo Thank you for the response! I realized I was using openfunctiondev/builder-java:v2-11 before, instead of openfunction/builder-java:v2-11, I really can't get the openfunction/builder-java, what's the difference between them.
But the openfunctiondev/builder-java:v2-11 can solve my problem for a while~

**Comment by benjaminhuo** [comment]
openfunction/builder-java is a repo name, you need to add a tag like v2-11 to access the docker image.

11 mean java 11, I think you can use higher versions of java such as `builder-java:v2-16`, `builder-java:v2-17` and `builder-java:v2-18`

**Comment by liililil** [comment]
@benjaminhuo I can find openfunctiondev/builder-java repo but not openfunction/builder-java repo.
![image](https://user-images.githubusercontent.com/100188324/181408055-7fdfda01-77b4-4fae-b3af-ffda6c33ffe9.png)
![image](https://user-images.githubusercontent.com/100188324/181408116-5f28577d-4c07-487e-9502-24a1f95ca162.png)

**Comment by benjaminhuo** [comment]
It doesn't matter whether you can search it.
The images can be used if you're able to pull it

```shell
docker pull openfunction/builder-java:v2-11
docker pull openfunction/builder-java:v2-16
docker pull openfunction/builder-java:v2-17
docker pull openfunction/builder-java:v2-18
```

**Comment by weiqiang-w** [comment]
@benjaminhuo  Did ofn support private harbor? 

Here is how i config the secret and deploy the function but failed at step-create. I use the harbor as  private registry.

**my config step:**

0. set the secret
```
kubectl create secret docker-registry push-secret \
 --docker-server=$REGISTRY_SERVER \
 --docker-username=$REGISTRY_USER \
 --docker-password=$REGISTRY_PASSWORD
```

1. Use IP address instead of hostname as access address for private image repository.
![image](https://github.com/OpenFunction/OpenFunction/assets/52819067/df61da31-c25f-4fe4-b967-e7d1b6be66fe)


2. skip tag-resolution

```
apiVersion: v1
data:
  registries-skipping-tag-resolving: 47.92.111.121:81
kind: ConfigMap
metadata:
  annotations:
    knative.dev/example-checksum: fa67b403
```


**and the error msg is** 

===> ANALYZING
ERROR: failed to get previous image: connect to repo store "47.92.111.121:81/openfunctiondev/demo-java": http: server gave HTTP response to HTTPS client
