### ISSUE TITLE
Function yaml file with build.shipwright cannot create Serverless Applications

### ISSUE THREAD

**Issue by fengpengyun** [OpenFunction/OpenFunction#412]
Description
Function yaml file with build.shipwright cannot create Serverless Applications

![1675668725692](https://user-images.githubusercontent.com/36986492/216911350-1281afff-3c18-4e64-95a1-7997beb75c96.jpg)

Environmental
- kubernetes version v1.21.14
- OpenFunction version 0.8.1

To Reproduce
[follow this](https://github.com/OpenFunction/samples/tree/main/apps/buildah/java)

**Comment by wanjunlei** [comment]
Run the following command.

```
kubectl get ClusterBuildStrategy buildah
```

If the buildah not found, create it by the following command.

```
kubectl apply -f https://raw.githubusercontent.com/OpenFunction/OpenFunction/main/config/strategy/build-strategy.yaml
```

**Comment by benjaminhuo** [comment]
> Run the following command.
> 
> ```
> kubectl get ClusterBuildStrategy buildah
> ```
> 
> If the buildah not found, create it by the following command.
> 
> ```
> kubectl apply -f https://raw.githubusercontent.com/OpenFunction/OpenFunction/main/config/strategy/build-strategy.yaml
> ```

@wrongerror @wanjunlei This (buildah clusterBuildStrategy) is not included in v0.8.1 installation?

**Comment by wrongerror** [comment]
Included: https://github.com/OpenFunction/charts/blob/main/openfunction/templates/build-strategies/buildah.yaml

**Comment by fengpengyun** [comment]
Configured with ClusterBuildStrategy build 
![1675671401248](https://user-images.githubusercontent.com/36986492/216921151-97433bfa-3d7d-4542-ad11-8b6885007a89.jpg)
@benjaminhuo

**Comment by benjaminhuo** [comment]
Take a look at the build logs:
`kubectl logs builder-<xxx> -c step-create`

**Comment by wanjunlei** [comment]
Please paste the yaml file of the function sample-java-app2.

**Comment by fengpengyun** [comment]
build logs:
![1675674183342](https://user-images.githubusercontent.com/36986492/216929861-1b7ce956-39f3-4ba1-8e58-a5ffd5b6f03b.jpg)

the yaml file of the function sample-java-app2：

```yaml
apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: sample-java-app2
  namespace: nocalhost
spec:
  version: "v1.0.0"
  image: "xxx/sample-java-app2:v1"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  build:
    builder: openfunction/buildah:v1.23.1
    shipwright:
      strategy:
        name: buildah
        kind: ClusterBuildStrategy
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "apps/buildah/java"
      revision: "main"
      credentials:
         name: xyiot-test-github-secret
  serving:
    annotations:
      openfunction.io/enable-dapr: "true"
    scaleOptions:
      minReplicas: 0
      maxReplicas: 5
    runtime: knative
    outputs:
      - name: target
        component: kafka-server
        operation: "create"
    bindings:
      kafka-server:
        type: bindings.kafka
        version: v1
        metadata:
          - name: brokers
            value: "10.233.70.69:9092"
          - name: authRequired
            value: "false"
          - name: publishTopic
            value: "sample-topic"
          - name: topics
            value: "sample-topic"
          - name: consumerGroup
            value: "function-front"
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent 
```

**Comment by benjaminhuo** [comment]
describe builder

**Comment by fengpengyun** [comment]
```yaml
Name:         builder-nv2w4
Namespace:    nocalhost
Labels:       openfunction.io/function=sample-java-app2
Annotations:  <none>
API Version:  core.openfunction.io/v1beta1
Kind:         Builder
Metadata:
  Creation Timestamp:  2023-02-06T09:02:20Z
  Generate Name:       builder-
  Generation:          1
  Managed Fields:
    API Version:  core.openfunction.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName:
        f:labels:
          .:
          f:openfunction.io/function:
        f:ownerReferences:
          .:
          k:{"uid":"a84a12ab-fbaf-4405-9439-a725035fd4dc"}:
            .:
            f:apiVersion:
            f:blockOwnerDeletion:
            f:controller:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        .:
        f:builder:
        f:image:
        f:imageCredentials:
          .:
          f:name:
        f:port:
        f:shipwright:
          .:
          f:strategy:
            .:
            f:kind:
            f:name:
        f:srcRepo:
          .:
          f:credentials:
            .:
            f:name:
          f:revision:
          f:sourceSubPath:
          f:url:
      f:status:
        .:
        f:phase:
        f:reason:
        f:resourceRef:
          .:
          f:shipwright.io/build:
          f:shipwright.io/buildRun:
        f:state:
    Manager:    openfunction
    Operation:  Update
    Time:       2023-02-06T09:02:21Z
  Owner References:
    API Version:           core.openfunction.io/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Function
    Name:                  sample-java-app2
    UID:                   a84a12ab-fbaf-4405-9439-a725035fd4dc
  Resource Version:        31756996
  UID:                     65f5e7e5-a98d-4f1c-80c3-2888c1a5963e
Spec:
  Builder:  openfunction/buildah:v1.23.1
  Image:    xxx/sample-java-app2:v1
  Image Credentials:
    Name:  push-secret
  Port:    8080
  Shipwright:
    Strategy:
      Kind:  ClusterBuildStrategy
      Name:  buildah
  Src Repo:
    Credentials:
      Name:           xyiot-test-github-secret
    Revision:         main
    Source Sub Path:  apps/buildah/java
    URL:              https://github.com/OpenFunction/samples.git
Status:
  Phase:   Build
  Reason:  UndefinedParameter
  Resource Ref:
    shipwright.io/build:     builder-nv2w4-build-ldff2
    shipwright.io/buildRun:  builder-nv2w4-buildrun-tq9wz
  State:                     Failed
Events:                      <none>
```

**Comment by wrongerror** [comment]
This is indeed a bug，please apply this yaml, then try again:
```yaml
apiVersion: shipwright.io/v1alpha1
kind: ClusterBuildStrategy
metadata:
  annotations:
    meta.helm.sh/release-name: openfunction
    meta.helm.sh/release-namespace: openfunction
  labels:
    app.kubernetes.io/managed-by: Helm
  name: buildah
spec:
  buildSteps:
  - args:
    - -c
    - |
      set -euo pipefail

      # Parse parameters
      context=
      dockerfile=
      image=
      buildArgs=()
      inBuildArgs=false
      registriesBlock=""
      inRegistriesBlock=false
      registriesInsecure=""
      inRegistriesInsecure=false
      registriesSearch=""
      inRegistriesSearch=false
      tlsVerify=true
      while [[ $# -gt 0 ]]; do
        arg="$1"
        shift

        if [ "${arg}" == "--context" ]; then
          inBuildArgs=false
          inRegistriesBlock=false
          inRegistriesInsecure=false
          inRegistriesSearch=false
          context="$1"
          shift
        elif [ "${arg}" == "--dockerfile" ]; then
          inBuildArgs=false
          inRegistriesBlock=false
          inRegistriesInsecure=false
          inRegistriesSearch=false
          dockerfile="$1"
          shift
        elif [ "${arg}" == "--image" ]; then
          inBuildArgs=false
          inRegistriesBlock=false
          inRegistriesInsecure=false
          inRegistriesSearch=false
          image="$1"
          shift
        elif [ "${arg}" == "--build-args" ]; then
          inBuildArgs=true
          inRegistriesBlock=false
          inRegistriesInsecure=false
          inRegistriesSearch=false
        elif [ "${arg}" == "--registries-block" ]; then
          inRegistriesBlock=true
          inBuildArgs=false
          inRegistriesInsecure=false
          inRegistriesSearch=false
        elif [ "${arg}" == "--registries-insecure" ]; then
          inRegistriesInsecure=true
          inBuildArgs=false
          inRegistriesBlock=false
          inRegistriesSearch=false
        elif [ "${arg}" == "--registries-search" ]; then
          inRegistriesSearch=true
          inBuildArgs=false
          inRegistriesBlock=false
          inRegistriesInsecure=false
        elif [ "${inBuildArgs}" == "true" ]; then
          buildArgs+=("--build-arg" "${arg}")
        elif [ "${inRegistriesBlock}" == "true" ]; then
          registriesBlock="${registriesBlock}'${arg}', "
        elif [ "${inRegistriesInsecure}" == "true" ]; then
          registriesInsecure="${registriesInsecure}'${arg}', "

          # This assumes that the image is passed before the insecure registries which is fair in this context
          if [[ ${image} == ${arg}/* ]]; then
            tlsVerify=false
          fi
        elif [ "${inRegistriesSearch}" == "true" ]; then
          registriesSearch="${registriesSearch}'${arg}', "
        else
          echo "Invalid usage"
          exit 1
        fi
      done

      # Verify the existence of the context directory
      if [ ! -d "${context}" ]; then
        echo -e "The context directory '${context}' does not exist."
        echo -n "ContextDirNotFound" > '$(results.shp-error-reason.path)'
        echo -n "The context directory '${context}' does not exist." > '$(results.shp-error-message.path)'
        exit 1
      fi
      cd "${context}"

      # Verify the existence of the Dockerfile
      if [ ! -f "${dockerfile}" ]; then
        echo -e "The Dockerfile '${dockerfile}' does not exist."
        echo -n "DockerfileNotFound" > '$(results.shp-error-reason.path)'
        echo -n "The Dockerfile '${dockerfile}' does not exist." > '$(results.shp-error-message.path)'
        exit 1
      fi

      echo "[INFO] Creating registries config file..."
      if [ "${registriesSearch}" != "" ]; then
        cat <<EOF >>/tmp/registries.conf
      [registries.search]
      registries = [${registriesSearch::-2}]

      EOF
      fi
      if [ "${registriesInsecure}" != "" ]; then
        cat <<EOF >>/tmp/registries.conf
      [registries.insecure]
      registries = [${registriesInsecure::-2}]

      EOF
      fi
      if [ "${registriesBlock}" != "" ]; then
        cat <<EOF >>/tmp/registries.conf
      [registries.block]
      registries = [${registriesBlock::-2}]

      EOF
      fi

      # Building the image
      echo "[INFO] Building image ${image}"
      buildah bud "${buildArgs[@]}" \
        --registries-conf=/tmp/registries.conf \
        --tag="${image}" \
        --file="${dockerfile}" \
        .

      # Push the image
      echo "[INFO] Pushing image ${image}"
      buildah push \
        --digestfile='$(results.shp-image-digest.path)' \
        --tls-verify="${tlsVerify}" \
        "${image}" \
        "docker://${image}"
    - --
    - --context
    - $(params.shp-source-context)
    - --dockerfile
    - $(build.dockerfile)
    - --image
    - $(params.shp-output-image)
    - --build-args
    - $(params.build-args[*])
    - --registries-block
    - $(params.registries-block[*])
    - --registries-insecure
    - $(params.registries-insecure[*])
    - --registries-search
    - $(params.registries-search[*])
    command:
    - /bin/bash
    image: quay.io/containers/buildah:v1.28.0
    name: build-and-push
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 65Mi
    securityContext:
      privileged: true
    workingDir: $(params.shp-source-root)
  parameters:
  - defaults:
    - annotation=module.wasm.image/variant=compat-smart
    description: The values for the args in the Dockerfile. Values must be in the
      format KEY=VALUE.
    name: build-args
    type: array
  - defaults: []
    description: The registries that need to block pull access.
    name: registries-block
    type: array
  - defaults: []
    description: The fully-qualified name of insecure registries. An insecure registry
      is one that does not have a valid SSL certificate or only supports HTTP.
    name: registries-insecure
    type: array
  - defaults:
    - docker.io
    - quay.io
    description: The registries for searching short name images such as `golang:latest`.
    name: registries-search
    type: array
  - default: ""
    description: Environment variables to set during _build-time_. The formate is
      `key1=value1,key2=value2`.
    name: ENV_VARS
```

**Comment by fengpengyun** [comment]
```yaml
Name:         builder-nv2w4
Namespace:    nocalhost
Labels:       openfunction.io/function=sample-java-app2
Annotations:  <none>
API Version:  core.openfunction.io/v1beta1
Kind:         Builder
Metadata:
  Creation Timestamp:  2023-02-06T09:02:20Z
  Generate Name:       builder-
  Generation:          1
  Managed Fields:
    API Version:  core.openfunction.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName:
        f:labels:
          .:
          f:openfunction.io/function:
        f:ownerReferences:
          .:
          k:{"uid":"a84a12ab-fbaf-4405-9439-a725035fd4dc"}:
            .:
            f:apiVersion:
            f:blockOwnerDeletion:
            f:controller:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        .:
        f:builder:
        f:image:
        f:imageCredentials:
          .:
          f:name:
        f:port:
        f:shipwright:
          .:
          f:strategy:
            .:
            f:kind:
            f:name:
        f:srcRepo:
          .:
          f:credentials:
            .:
            f:name:
          f:revision:
          f:sourceSubPath:
          f:url:
      f:status:
        .:
        f:phase:
        f:reason:
        f:resourceRef:
          .:
          f:shipwright.io/build:
          f:shipwright.io/buildRun:
        f:state:
    Manager:    openfunction
    Operation:  Update
    Time:       2023-02-06T09:02:21Z
  Owner References:
    API Version:           core.openfunction.io/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Function
    Name:                  sample-java-app2
    UID:                   a84a12ab-fbaf-4405-9439-a725035fd4dc
  Resource Version:        31756996
  UID:                     65f5e7e5-a98d-4f1c-80c3-2888c1a5963e
Spec:
  Builder:  openfunction/buildah:v1.23.1
  Image:    xxx/sample-java-app2:v1
  Image Credentials:
    Name:  push-secret
  Port:    8080
  Shipwright:
    Strategy:
      Kind:  ClusterBuildStrategy
      Name:  buildah
  Src Repo:
    Credentials:
      Name:           xyiot-test-github-secret
    Revision:         main
    Source Sub Path:  apps/buildah/java
    URL:              https://github.com/OpenFunction/samples.git
Status:
  Phase:   Build
  Reason:  UndefinedParameter
  Resource Ref:
    shipwright.io/build:     builder-nv2w4-build-ldff2
    shipwright.io/buildRun:  builder-nv2w4-buildrun-tq9wz
  State:                     Failed
Events:                      <none>
```
