### ISSUE TITLE
how to config maven settings.xml during the building phase when use maven package a java project .

### ISSUE THREAD

**Issue by weiqiang-w** [OpenFunction/OpenFunction#449]
1. if i use maven to build java project .How can i change the mirror in settings.xml or import external setting.xml files during the building phase ?

2. Is ofn allowed to mount the local maven repositories ?

**Comment by wanjunlei** [comment]
> 1. if i use maven to build java project .How can i change the mirror in settings.xml or import external setting.xml files during the building phase ?
> 2. Is ofn allowed to mount the local maven repositories ?

1. Now it does not support modifying the `setting.xml` of maven.
2. No, you can use `cache-image` to speed up the building.

First, update the strategy

```
kubectl apply -f https://raw.githubusercontent.com/OpenFunction/OpenFunction/main/config/strategy/build-strategy.yaml
```

Then, set the `cache-image` in the function as following:

```
apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: function-http-java
spec:
  version: "v2.0.0"
  image: "openfunctiondev/sample-java-func:v1"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  build:
    builder: openfunction/builder-java:v2-18
    env:
      FUNC_NAME: "dev.openfunction.samples.HttpFunctionImpl"
      FUNC_CLEAR_SOURCE: "true"
    params:
      CACHE-IMAGE: < cache image >
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/knative/java"
      revision: "main"
```

The  `cache-image` include the maven dependencies, the builder will restore the layer from it. If  `cache-image` does not exist or changed, it will be updated after building.
