### ISSUE TITLE
BaaS integration with nginx or other serverless apps which are not functions

### ISSUE THREAD

**Issue by yairyairyair** [OpenFunction/OpenFunction#465]
Hi, 

I think that dapr does not work with nginx for example a cron @every 2s trigger.
I dont know if its because the openfunction functions-framework does not build this image so does not have the dapr bindings code.
Is there a way to get this to work?

Attaching my yaml:

```
apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: dapr-test
  namespace: delthis
spec:
  image: "nginx"
  serving:
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
    bindings:
      cron:
        metadata:
          - name: schedule
            value: "@every 2s"
        type: bindings.cron
        version: v1
    triggers:
      dapr:
        - name: cron
      http:
        port: 80
```
