### ISSUE TITLE
创建同步函数失败 

### ISSUE THREAD

**Issue by mzychaco** [OpenFunction/OpenFunction#471]
**Description**
按照官网指引安装好openfunction，过程符合官网描述，没什么问题，然后我尝试创建一个简单的同步函数，yaml如下：
```
apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: function-sample
spec:
  image: "<本地仓库的镜像地址>"
```
然后执行kubectl apply -f xxx.yaml
但报错返回：
```
Error from server (InternalError): error when creating "test-go-func.yaml": Internal error occurred: failed calling webhook "mfunctions.of.io": failed to call webhook: Post "https://openfunction-webhook-service.openfunction.svc:443/mutate-core-openfunction-io-v1beta2-function?timeout=10s": EOF
```

请问该如何解决？

**Environmental**
Tell us what your cluster environment is like, e.g.

- Operating System Information：Linux version 4.19.0-amd64-desktop
- kubernetes version： 1.27.3
- minikube： 1.31.0
- OpenFunction version:  v1.1.x
- Versions of dependent components (e.g. dapr, keda, shipwright, knative)

**Expected behavior**
Tell us what should happen.

**Actual behavior**
Tell us what happens instead. Provide a log message if relevant.

**To Reproduce**

1. '..'
2. '...'
3. '....'

**Screenshots**

**Additional context**

**Comment by vfarcic** [comment]
Experiencing the same issue.

**Comment by benjaminhuo** [comment]
> 按照官网指引安装好openfunction，过程符合官网描述，没什么问题，然后我尝试创建一个简单的同步函数，yaml如下：

按照官网的哪篇文档创建的函数？完整的 yaml 贴出来

试过这里的例子吗？
https://openfunction.dev/docs/getting-started/quickstarts/sync-functions/

**Comment by mzychaco** [comment]
The problem has been resolved. The YAML I was using was incomplete; the official documentation provides only partial content. To make it work, I need to use the complete function definition YAML.

**Comment by uestczz** [comment]
@benjaminhuo I meet this too. my system is Ubuntu 22.04 LTS. k8s v1.22.2. I use helm to install openfunction.  I use the hello word yaml.
```
apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: function-sample
spec:
  version: "v2.0.0"
  image: "openfunctiondev/sample-go-func:v1"
  imageCredentials:
    name: push-secret
  build:
    builder: openfunction/builder-go:latest
    env:
      FUNC_NAME: "HelloWorld"
      FUNC_CLEAR_SOURCE: "true"
      # # Use FUNC_GOPROXY to set the goproxy if failed to fetch go modules
      # FUNC_GOPROXY: "https://goproxy.cn"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/knative/hello-world-go"
      revision: "main"
  serving:
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
    triggers:
      http:
        port: 8080
```
