### ISSUE TITLE
OpenFunction 1.2.0 imageCredentials pull  private images fail

### ISSUE THREAD

**Issue by xuybin** [OpenFunction/OpenFunction#501]
**Description**
imageCredentials pull  private images fail.

**Environmental**
Tell us what your cluster environment is like, e.g.

- Operating System Information
- kubernetes v1.27.3
- OpenFunction 1.2.0
- Versions of dependent components (e.g. dapr, keda, shipwright, knative)

**Expected behavior**
use imageCredentials  pull  private images ok

**Actual behavior**
Tell us what happens instead. Provide a log message if relevant.

**To Reproduce**
```yaml
apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: sample-node-keda
  namespace: keda # must be in the same namespace with keda http-addon
spec:
  version: "v2.0.0"
  #image: "stefanprodan/podinfo:latest" #使用此配置，正常启动函数
  image: "xuybin/podinfo:latest" #在hub.docker.com设置为公开时，正常启动
  imageCredentials: #设置成私有，加此配置，报拉取失败
    name: push-secret-docker #反复确认密钥正确，使用它成功打包了函数并上传到同名仓库
  serving:
    triggers:
      http:
        engine: "keda" # optional, default to knative if not set
        port: 9898
        route:
          gatewayRef:
            name: openfunction
            namespace: openfunction
          # hostnames:
          #   - "podinfo.com"
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /
    scaleOptions:
      minReplicas: 1
      maxReplicas: 10
      keda:
        httpScaledObject:
          targetPendingRequests: 100 # Default 100
          cooldownPeriod: 60 # Default 300
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
```
. See error

**Screenshots**
![image](https://github.com/OpenFunction/OpenFunction/assets/10354549/d2de3156-fdc4-4d4d-8964-023c06b67421)
![image](https://github.com/OpenFunction/OpenFunction/assets/10354549/981820b7-4141-4883-841b-3aad814b67af)
![image](https://github.com/OpenFunction/OpenFunction/assets/10354549/addea930-2f98-45ef-ada9-f1ba3d9b09a4)

**Additional context**
