### ISSUE TITLE
Allow Dapr to use http protocol for functions

### ISSUE THREAD

**Issue by salaboy** [OpenFunction/OpenFunction#515]
**Description**

Working with async functions and trying to publish events using the Dapr APIs is impossible with the current setup. 

Currently, dapr sidecars are started with app-protocol `grpc`. This limits the connections to deliver events to the application to have a grpc endpoint that requires a bidirectional connection to be open between the function and the sidecar. 

This is a problem because the function might be downscaled (and even if the mode is set to standalone, the channel will be closed). 
Allowing HTTP app-protocol will enable the dapr sidecar to send an http requests to the function that will work even if the function was downscaled.

**Comment by wrongerror** [comment]
You can configure the Dapr sidecar’s protocol by setting the annotations in OpenFunction. The annotation is: dapr.io/app-protocol: http. This will allow you to use the Dapr API to publish events to asynchronous functions. 

```yaml
apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: cron-input-kafka-output
spec:
  serving:
    annotations:
      openfunction.io/enable-dapr: "true"
      dapr.io/app-protocol: "http"
  ...
```
